### ISSUE TITLE
DeinterlaceII, Smart Deinterlace, VHS, VHSII & VHSIII for x64

### ISSUE THREAD

**Issue by 03stevensmi** [jpsdr/Filtres_JPSDR#2]
hello,
would it be ok if you could build DeinterlaceII, Smart Deinterlace, VHS, VHSII & VHSIII for x64?

I use them all the time on 32bit but i now need them for 64bit.

Would that be ok?

Thank You.

Michael .S

**Comment by jpsdr** [comment]
DeinterlaceII, Smart Deinterlace didn't produce satisfacting results. More, they can produce bad result introducing very annoying issues. One of them, is that if you have noise (even a little) you can have, even if the picture don't change, because of the noise, the threshold reached or not between successive frame, resulting flickers (one frame is deinterlaced, the next not, the next yes, the next not,...).
VHS and co are very low quality denoise filters i've made a verryyy looong time ago (when VHS where still in used). I have since found out an excelent denoise filter which is thousand time better that my VHS filters.
As for these filters making a 64 bits version will require time, and i absolutely don't care anymore for them, i will not not it.

**Comment by 03stevensmi** [comment]
ok, thanks anyway, bbut if it makes you feel any appretiantion... the vhsiii filter is litrally one of my best and most used
filter for my projects. its litrally the only filter fast enough to do the analog re-productions and give a propper pal
sattelite feel when used with captain jack's videocrypt filter.

without your vhs iii filter,
i would have not came this far forward in my video production and it may not be used as it was intended,
but for messing with pal, its a godsend.
the deinterlace filters are... meh. its the pal movie deinterlacer filter i really need for 64bit but the dev hasnt updated it
since the milenium.

but thats just the deinterlce filter.

i 100% support that you dont like or care enough for them just for 1 person, noty worth the hassle.
but i really do want to clearly state that your vhsiii filter has made miricles that litrally no other filter can do
when used with videocrypt filter and analog recreation.


so for that, i must say thank you.
even mistakes have alternative uses.
;)
